# Generated by Django 4.2 on 2025-11-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_item_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_cal',
            field=models.IntegerField(default=0),
        ),
    ]
