# Generated by Django 4.2 on 2025-12-03 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0006_item_item_cal'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='favourites',
            field=models.ManyToManyField(blank=None, default=None, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
