# Generated by Django 6.0 on 2025-12-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_rename_author_item_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='auther',
            new_name='author',
        ),
    ]
