# Generated by Django 6.0 on 2025-12-23 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_item_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='author',
            new_name='auther',
        ),
    ]
