# Generated by Django 6.0 on 2025-12-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_rename_auther_item_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
