# Generated by Django 4.2 on 2025-12-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_item_item_cal'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favourite_food',
            field=models.ManyToManyField(blank=True, related_name='favourited_by_users', to='food.item'),
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_food',
            field=models.ManyToManyField(blank=True, related_name='liked_by_users', to='food.item'),
        ),
    ]
