# Generated by Django 4.2 on 2025-12-03 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_favourite_food_profile_liked_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favourite_food',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='liked_food',
        ),
    ]
